title: 'Cryptic Coder'
default_lang: en
author:
  name: 'Cryptic Coder'
  email: mahbub.kuet@gmail.com
  copyright: 'Contact Me: iamcrypticcoder@gmail.com'
taxonomies:
  - category
  - tag
metadata:
  description: 'Cryptic Coder'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
routes:
  /something/else: /blog/sample-3
  /another/one/here: /blog/sample-3
  '/new/*': '/blog/*'
blog:
  route: /blog
social:
  -
    url: 'https://twitter.com/getgrav'
    icon: twitter
  -
    url: 'https://www.facebook.com/cryptic.coder'
    icon: facebook
  -
    url: blog.rss
    icon: rss
contact:
  address:
    -
      line: '222 Ave C South'
    -
      line: 'Saskatoon, Saskatchewan'
    -
      line: 'Canada S7K 2N5'
  gps: 1.306.222.3456
othermenu:

quicklinks:
  -
    text: Amazon Web Service
    url: 'base_url:aws'
  -
    text: Algorithms
    url: 'base_url:algorithms'
  -
    text: Mathematics
    url: 'base_url:mathematics'
  -
    text: UVA Solution
    url: 'base_url:uva solution'
header_options:
  arrows: 'false'
  autoslide: 'false'
  autoslideHoverStop: 'false'
  interval: '2000'
  loop: 'false'
  transition: zoom
  itemsForSlide: '0'
  touch: 'true'
  swipe: 'true'
footer:
  description: ''
  contact_title: 'Contact Info'
  links_title: 'Quick Links'
  newsletter_title: Newsletter
  newsletter_description: 'Enter your email address to subscribe to this blog and receive notifications of new posts by email.'
  copyright_text: ''
  feedburner: ''
