title: 'Cryptic Coder'
default_lang: en
author:
  name: 'Cryptic Coder'
  email: mahbub.kuet@gmail.com
  copyright: 'Copyright 2013 Deliver. All Rights Reserved.'
taxonomies:
  - category
  - tag
metadata:
  description: 'My Deliver Site'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
routes:
  /something/else: /blog/sample-3
  /another/one/here: /blog/sample-3
  '/new/*': '/blog/*'
blog:
  route: /blog
social:
  -
    url: 'https://twitter.com/getgrav'
    icon: twitter
  -
    url: '#'
    icon: facebook
  -
    url: blog.rss
    icon: rss
contact:
  address:
    -
      line: '222 Ave C South'
    -
      line: 'Saskatoon, Saskatchewan'
    -
      line: 'Canada S7K 2N5'
  gps: 1.306.222.3456
othermenu:
  -
    text: About
    url: about
  -
    text: 'Privacy Policy'
    url: '#'
  -
    text: Contact
    url: contact
quicklinks:
  -
    text: Portfolio
    url: 'base_url:portfolio'
  -
    text: About
    url: 'base_url:about'
  -
    text: Services
    url: 'base_url:services'
  -
    text: Archive
    url: 'base_url:archive'
  -
    text: Blog
    url: 'base_url:blog'
  -
    text: 'Contact Us'
    url: 'base_url:contact'
header_options:
  arrows: 'false'
  autoslide: 'false'
  autoslideHoverStop: 'false'
  interval: '2000'
  loop: 'false'
  transition: zoom
  itemsForSlide: '0'
  touch: 'true'
  swipe: 'true'
footer:
  description: 'This is footer description'
  contact_title: 'Contact Info'
  links_title: 'Quick Links'
  newsletter_title: Newsletter
  newsletter_description: 'Etiam porta sem malesuada magna mollis euismod.'
  copyright_text: 'Copyright 2013 Deliver. All Rights Reserved.'
  feedburner: ''
